sudo: true

language: generic # We build in Docker

services:
 - docker

script:
 - set -e # Fail fast
 - TAG=dev make docker-build # Build binary and run unit tests
 - TAG=dev make docker-push # Push :dev image to registry