sudo: true

language: go
go:
 - 1.11.x

services:
 - docker

jobs:
  include:
    - stage: bootstrap-build-test
      script:
        - make vendor
        - make build
        - make test
      after_success:
        - make build-img
        - make push-img