trigger:
  tags:
    include:
      - v.*
  branches:
    include:
      - develop
      - master
  paths:
    exclude:
      - README.md

pr:
  - master

variables:
  repository: 'focal-freedom-236620/scheduler'
  type: $(Build.SourceBranchName)
  commit: $(Build.SourceVersion)

jobs:
  - job: Platform
    dependsOn: Scheduler
    pool: server

    steps:
      - task: InvokeRESTAPI@1
        displayName: 'trigger platform job'
        inputs:
          connectionType: 'connectedServiceName'
          serviceConnection: 'Pipelines'
          method: 'POST'
          urlSuffix: '/edgeworx/_apis/build/builds?api-version=5.0'
          body: "{\"Parameters\":\"{\\\"images.scheduler\\\": \\\"gcr.io/$(repository):dev-$(commit)\\\"}\", \"Definition\":{\"id\":\"5\"}}"
          waitForCompletion: 'false'

  - job: Scheduler
    pool:
      vmImage: 'Ubuntu-16.04'
    
    steps:
      - task: Docker@2
        displayName: 'build docker'
        inputs:
          containerRegistry: 'Edgeworx GCP'
          repository: $(repository)
          command: 'build'
          Dockerfile: 'Dockerfile'
          tags: |
            dev-$(commit)
            dev-$(type)
            dev-latest
    
      - task: Docker@2
        displayName: 'push docker'
        inputs:
          containerRegistry: 'Edgeworx GCP'
          repository: $(repository)
          command: 'push'
          Dockerfile: 'Dockerfile'
          tags: |
            dev-$(commit)
            dev-$(type)
            dev-latest