[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.10"

[[constraint]]
  name = "k8s.io/kubernetes"
  branch = "release-1.10"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.10"

[[constraint]]
  name = "k8s.io/apiserver"
  branch = "release-1.10"

[[constraint]]
  name = "k8s.io/client-go"
  version = "7.0.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"
